PROJ := hello
PIN_DEF := ../icebreaker.pcf
DEVICE := up5k

FREQ := 58

V_SRC := hello.v

SIM_SRC := test.cpp \
		/usr/share/verilator/include/verilated.cpp \
		/usr/share/verilator/include/verilated_vcd_c.cpp



INC_DIR := obj_dir \
		/usr/share/verilator/include \
		..		 

include ../main.mk
